#!/bin/bash

add_commit_push() {
    task_number=$1
    commit_message=$2

    git add ${task_number}-*
    git commit -m "${commit_message}"
    git push
}

add_commit_push "0" "Adding Task 0 Executing basic javascript with Node JS"
add_commit_push "1" "Adding Task 1 Using Process stdin"
add_commit_push "2" "Adding Task 2 Reading a file synchronously with Node JS"
add_commit_push "3" "Adding Task 3 Reading a file asynchronously with Node JS"
add_commit_push "4" "Adding Task 4 Create a small HTTP server using Node's HTTP module"
add_commit_push "5" "Adding Task 5 Create a more complex HTTP server using Node's HTTP module"
add_commit_push "6" "Adding Task 6 Create a small HTTP server using Express"
add_commit_push "7" "Adding Task 7 Create a more complex HTTP server using Express"

git add full_server/*
git commit -m "Adding Task 8 Organize a complex HTTP server using Express"
git push

git add .
git commit -m "Adding Resources and Requirements"
git push